BASE_URL="https://api.spotify.com/v1"
PLAYLIST_MODIFY_PUBLIC = "playlist-modify-public"
PLAYLIST_MODIFY_PRIVATE = "playlist-modify-private"
PLAYLIST_READ_PUBLIC = "playlist-read-public"
PLAYLIST_READ_PRIVATE = "playlist-read-private"
PLAYLIST_READ_COLLABORATIVE = "playlist-read-collaborative"