CLIENT_ID="6d30aff25a6d4e0fa8312a8dc3ccdfe6"
CLIENT_SECRET="bf6a4b3f42014c21978d7128b1b723ba"
CALLBACK_URI="http://myspotify.com/callback/"
LOGIN_BASE_URL="https://accounts.spotify.com"
BASE_URL="https://api.spotify.com/v1"

PLAYLIST_MODIFY_PUBLIC = "playlist-modify-public"
PLAYLIST_MODIFY_PRIVATE = "playlist-modify-private"
PLAYLIST_READ_PUBLIC = "playlist-read-public"
PLAYLIST_READ_PRIVATE = "playlist-read-private"